### PR TITLE
CTFE Fibonacci

### PR DESCRIPTION
**Pull request by JinShil**
This will probably be a better test than https://github.com/CyberShadow/TrenD/pull/1

### CODE REVIEW

**Comment by JinShil** [comment]
I made it 1000 as that seemed to be the default CTFE recursion limit.

**Comment by CyberShadow** [comment]
> It overflows too quickly.

Well, the multiplication itself is going to take the same amount of time at compilation and runtime.

But this isn't very typical CTFE code. I think it would be more interesting to benchmark something closer to what people write when they start running into CTFE performance issues. Generating code for string mixins, perhaps? At least that touches on the problem that arrays are copied when one element is modified (IIRC).

I was hopeful people e.g. involved with Vibe and Diet templates could provide some micro-benchmarks. @MartinNowak @sludwig ideas?

**Comment by s-ludwig** [comment]
It should be pretty easy to rip out just the Diet parser code and process some real-world template with it, there are no serious dependencies to any other vibe.d code. I could have a look at that.

**Comment by CyberShadow** [comment]
Ideally it shouldn't depend on recent compiler features or bugfixes, so that we have better historical data.

**Comment by s-ludwig** [comment]
It currently is tested from 2.065-2.067, but it should compile or be easy to get to compile down to maybe 2.062, not sure (I think around 2.059 was the first version on which the original code used to work, but I've removed some workarounds since then). Would that be enough?

**Comment by CyberShadow** [comment]
Well, 2.059 would give us a time range of about 3 years, 2 years with 2.062. Current tests go back to 2012, and 2011 should also be covered when I fix the thing trying to build rdmd (which was broken for long periods of time). It's enough to have perspective for future changes, but maybe we could also have simpler micro-benchmarks.

**Comment by s-ludwig** [comment]
Good micro benchmarks would certainly be nice to have, but a larger real world example certainly also has its merit*. The only issue is that the benchmark that I prepared now contains almost 3k LoC, certainly too much to put into an inline string. How to go about this? Declare a separate module with a huge `q{}` string, use a string import, or just drop it?

BTW, it requires at least DMD 2.061 (01/01/2013), which should already show quite an interesting history. Supporting 2.060 and below would require some larger refactoring.

\* A micro benchmark that presumably best matches the Diet compiler would be to assemble a string of "lines" (or whatever kind of separator, using `~=`) and then split it up into an array of lines (at CT).

**Comment by CyberShadow** [comment]
> How to go about this? Declare a separate module with a huge q{} string, use a string import, or just drop it?

Probably better to just make the ProgramInfo array non-const and read it in in a static ctor, to avoid requiring -J. Just upload it wherever and I'll add it.

**Comment by s-ludwig** [comment]
https://gist.github.com/s-ludwig/52e3adc60e0e38bafb6b

**Comment by CyberShadow** [comment]
Added... you can see some preliminary results already:
http://digger.k3.1azy.net/trend/

**Comment by s-ludwig** [comment]
Interesting! I would have never imagined that compilation time has actually stayed that constant over time (except for 2.067.x, which is fortunately already fixed again).

**Pull request closed without merging**
